id = "htmlhugo"
name = "HTML_Plus_Hugo"
description = "hugo support"
version = "0.0.1"
schema_version = 1
authors = ["ChatGPT, but asked by GitesHubisz <https://github.com/GitesHubisz>"]

[grammars.htmlhugo]
repository = "https://github.com/GitesHubisz/tree-sitter-html"
commit = "34d6fb321e7b5081cedd4c68449ba84a02f49e9d"
