name = "HTMLhugo"
grammar = "htmlhugo"
path_suffixes = ["html", "htm", "shtml"]
block_comment = ["<!-- ", " -->"]
brackets = [
    { start = "{{", end = "}}", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "!--", end = " --", close = true, newline = false, not_in = ["comment", "string"] },
]
word_characters = ["-"]
prettier_parser_name = "html"
